# Data Generation Parameters
data_generation:
  cifar_path: './data'
  eta: 0.2

# Training Hyperparameters
training:
  num_classes: 10
  batch_size: 512
  epochs: 1000
  learning_rate: 0.001

pico:
  low_dim: 128
  moco_queue: 8192
  moco_m: 0.999
  proto_m: 0.99
  prot_start: 1 # Start prototype learning early for faster convergence
  loss_weight: 0.5
  conf_ema_range: [0.95, 0.8]

solar:
  warmup_epoch: 50
  rho_range: [0.2, 0.6]
  lamd: 3
  eta: 0.9
  tau: 0.99
  est_epochs: 100  # pre-estimation stage
  gamma1: 0.1     # first stage empirical distribution update
  gamma2: 0.01    # second stage empirical distribution update